### PR TITLE
rename code_admin to blacklist_manager

### PR DESCRIPTION
**Pull request by snpd25**
Fixes issue #318

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
Looks good to start. You'll also need to create a migration to rename the role in the database - just running `Role.where(name: 'code_admin').update(name: 'blacklist_manager')` should do it.

**Comment by makyen** [comment]
BTW: The CI issues in the master branch have been resolved. So that CI is more useful in this PR, I'd suggest you either merge in the master branch, or rebase to the current master HEAD commit.

Note that there remains an intermittent Mysql2 failure in the rails-tests.

**Comment by snpd25** [comment]
@ArtOfCode- , I got this error while running `rake db:migrate` :
`SQLite3::SQLException: no such column: feedbacks.is_invalidated: SELECT COUNT(*) AS count_all, posts.id AS posts_id FROM "feedbacks" INNER JOIN "posts" ON "posts"."id" = "feedbacks"."post_id" WHERE "feedbacks"."is_invalidated" = ? AND (feedback_type LIKE '%tp%') GROUP BY posts.id`

**Comment by ArtOfCode-** [comment]
Sounds like you don't have the database set up correctly - try running `rails db:drop` followed by `rails db:create` and `rails db:schema:load` again to set it up correctly. I'd advise also using MySQL not SQLite - nothing in metasmoke is tested against SQLite, so it's likely to break in unknown ways.

**Comment by snpd25** [comment]
@ArtOfCode- I am currently facing issues in setting up mysql server. For the time being I have uploaded the migration file. Please review this.

**Comment by ArtOfCode-** [comment]
Looks good on the surface. I'll need to pull it to a development environment and test manually before we merge - I'll try to do that tonight, but it may be a little later this week.

**Comment by ArtOfCode-** [comment]
Looks okay to me. I've tested as much as I can and nothing seems to be broken, so I'm going to merge this to a feature branch for now while we update other projects to match.

Thanks for your contribution!

**Pull request merged**
