### PR TITLE
Switch to a Unicode flag

### PR DESCRIPTION
**Pull request by j-f1**
This makes the icon the same one used in the autoflagging userscript.

Ref: https://chat.stackexchange.com/transcript/message/35234625

### CODE REVIEW

**Comment by Undo1** [comment]
Added a simple style to make it the correct size. I'm indifferent on whether we need this to be consistent, would appreciate other's input ( @ArtOfCode- ?). Difference:

screen shot 2017-02-12 at 9 26 39 pm

screen shot 2017-02-12 at 9 26 25 pm

**Comment by angussidney** [comment]
Is this really necessary? Given the screenshot you provided, the glyphicon flag looks better at this size

**Comment by j-f1** [comment]
@angussidney https://chat.stackexchange.com/transcript/message/35234639#35234639:

> [T]he problem is that 'a flag' can mean a manual flag and an autoflag.

**Comment by ArtOfCode-** [comment]
The glyhphicon flag *does* look better here. Do we have anywhere that we use a flag symbol to indicate a manual flag? If we do, then I can see a decent argument for changing to the Unicode flag so we support filled and empty variants; if not, maybe we don't need this (yet, at least).

**Comment by Undo1** [comment]
Closing for now; we can revisit this later if necessary.

**Pull request closed without merging**
