### PR TITLE
Drop the percentage marks from REGEXP

### PR DESCRIPTION
**Pull request by iBug**
I thought it was some kind of Ruby syntax but it turned out it's not, after reading a few pages of Ruby rookie tutorials...

### CODE REVIEW

**Comment by Undo1** [comment]
LGTM without testing, have you tested it?

**Comment by iBug** [comment]
Uh... I don't even have a complete Ruby developing environment...

**Comment by ArtOfCode-** [comment]
Having one might be a good idea :P

**Comment by iBug** [comment]
@ArtOfCode- I don't even know Ruby at all... I've never studied it. I doubt a complete Ruby developing environment would be helpful to me, a freshman at a university... Anyway, does this pull look good?

**Comment by ArtOfCode-** [comment]
What Undo said - looks good in principle, but if you haven't tested it then it needs to wait until someone can pull and test it before merge.

**Comment by NobodyNada** [comment]
@iBug If you're looking for a quick way to test the PR without spending half an hour to set up a full MS development environment, I'd suggest [using Docker](https://stackoverflow.com/c/charcoal/a/260/7).  With one command, it will set up a complete metasmoke environment from scratch in an isolated container in about 5 minutes.

**Comment by iBug** [comment]
@NobodyNada If only you could run Docker on an Android phone.

@ArtOfCode- I replaced `"#{something}"` with `something.to_s` and it looks better now.

**Comment by angussidney** [comment]
.....why are you coding on a phone?

**Comment by tripleee** [comment]
The fact is that the current code is broken; it reports "0 TP, 0 FP, 0 NAA" on every generated pull request.  Testing this without having access to Github seems hard, even if you can get Metasmoke up and running, but I concur: The syntax 'body REGEXP ?', '%hello%' is not correct SQL for finding `hello` in `body`. This seems to be a holdover from an earlier version where the code had `body LIKE ?` where you do want the percentage marks (I think).

**Comment by tripleee** [comment]
Unfortunately, we still get "0 TP, 0 FP, 0 NAA". I'll belatedly create an issue to track that.

**Pull request merged**
