### PR TITLE
createdb: remove import files to save disk space

### PR DESCRIPTION
**Pull request by tripleee**
(closes: #900) or at least alleviates the problem somewhat

### CODE REVIEW

**Comment by makyen** [comment]
This appears to be deleting the original database backup files. I don't like the idea of auto-deleting these files which the build process didn't create, particularly doing so without notice to the human and without the human being given the option not to do so. If these were my only copies of the database backup files, I'd be fairly pissed that they were auto-deleted. I might be using a database backup from a specific prior date, which could be impossible to replace.

**Comment by makyen** [comment]
The parent commit for these changes is 3 months old. Please pull the current version of the repository's master branch and rebase your changes to that commit, so that CI testing functions correctly.

If you choose not to do that, then given how GitHub performs merges, please don't use "create a merge commit". Please select "Rebase and merge" when choosing how to merge. GitHub generally does a merge of the master branch into the PR, rather than just the PR into master. Doing that can result in a commit which is confusing when looking at the diffs, as it will look like you're re-making every change between the commit upon which this is parented and the current HEAD of the master branch.

**Comment by tripleee** [comment]
> This appears to be deleting the original database backup files. I don't like the idea of auto-deleting these files which the build process didn't create, particularly doing so without notice to the human and without the human being given the option not to do so. If these were my only copies of the database backup files, I'd be fairly pissed that they were auto-deleted. I might be using a database backup from a specific prior date, which could be impossible to replace.

The script supposed to run inside the Docker image, which contains a copy from the `COPY . .` earlier in the file.  Perhaps there should be a guard against running it outside the image, though.

**Comment by tripleee** [comment]
> The parent commit for these changes is 3 months old. Please pull the current version of the repository's master branch and rebase your changes to that commit, so that CI testing functions correctly.

Done, thanks. Sorry, I thought I pulled upstream before creating a branch, but apparently not.

**Comment by makyen** [comment]
It doesn't appear that the current version of the repository was pulled and `git rebase master` run. The [parent commit](https://github.com/Charcoal-SE/metasmoke/commit/7bb8431e3e638cbbed06e75c7b54b86f52d48ecc) for this PR is still the same.

**Comment by tripleee** [comment]
Grrr, I had used really dumb remote names in the distant past which tripped me up. That also explains why the branch for this got pushed to the main repo, rather than my personal fork.

**Pull request merged**
