### PR TITLE
Attempt to fix CircleCI timeout by increasing allowed time

### PR DESCRIPTION
**Pull request by iBug**
As the title says

### CODE REVIEW

**Comment by iBug** [comment]
Obviously it doesn't work. I'll try something else later.

**Comment by quartata** [comment]
if it's taking longer than 20 minutes something is dreadfully wrong, we should not try to monkey patch over this

**Comment by iBug** [comment]
@thesecretmaster Just leave this closed for now. I'll continue to try to fix the issue and I'll ping you when I finally make it.

**Comment by thesecretmaster** [comment]
Ok, I should also get notifications for this PR.

**Pull request closed without merging**
