### PR TITLE
Raise exception on protect_from_forgery

### PR DESCRIPTION
**Pull request by user12986714**
Make sure the session hard fails.

### CODE REVIEW

**Comment by thesecretmaster** [comment]
Is there a problem with the default, null_session approach?

**Comment by user12986714** [comment]
That .verify_code() method looks susceptible to request forging; however I am not quite sure what the :null_session really does & if it is secure

**Comment by ArtOfCode-** [comment]
`null_session` drops the session cookie, i.e. logs the user out... but that's not the default approach; `exception` is. This is already protected by exception.

**Comment by thesecretmaster** [comment]
@ArtOfCode- [Are you sure?](https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/request_forgery_protection.rb#L134)

**Comment by ArtOfCode-** [comment]
@thesecretmaster Pretty sure; I seem to remember the Rails docs saying `null_session` is the default for API apps, but `exception` is the default for web apps.

**Pull request closed without merging**
