### PR TITLE
protect_from_forgery

### PR DESCRIPTION
**Pull request by user12986714**
Especially the .destroy() method

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
Have you tested that this works/doesn't break anything?

**Comment by user12986714** [comment]
Nope, but it *should* be good since no one should be creating/deleting a user without an authenticated session; but without testing I am not quite sure either.

**Comment by ArtOfCode-** [comment]
Let me just check: do you understand what `protect_from_forgery` is doing?

**Comment by user12986714** [comment]
It will add a `_csrf_token` and validate against it, so to make sure the session is not forged.

**Comment by ArtOfCode-** [comment]
What does "the session is not forged" mean, though? It sounds like you have a misunderstanding of the attack vector this is protecting against - have a look at what CSRF is.

**Comment by user12986714** [comment]
Not valid

**Pull request closed without merging**
