### PR TITLE
Hey this might actually work

### PR DESCRIPTION
**Pull request by ArtOfCode-**
Adds two-factor authentication via mobile authenticator app (tested with Google Authenticator).

Lotta *stuff* in this, and it's login code, so I'm leaving it here for review.

### CODE REVIEW

**Comment by Undo1** [comment]
I wonder, is this testable? It'd be nice to have tests on something this big.

**Comment by ArtOfCode-** [comment]
Um. Depends on your definition of "possible"... I mean, if you want to emulate an Android device and screen-scrape and run optical character recognition on screenshots, yeah it's testable ;)

**Comment by Undo1** [comment]
Can't go that deep, I was thinking more something that just checks login flow and spoofs whatever codes are necessary.

**Comment by ArtOfCode-** [comment]
We can have regular tests, of course - "does this action add a code to this model". Now I think about it, it actually might be possible to test the 2FA element, too, since we can just use the same library to generate the necessary 2FA codes.

**Comment by Undo1** [comment]
Welp, why not try it.

**Pull request merged**
