### PR TITLE
Combined fix for Mimemagic issue

### PR DESCRIPTION
**Pull request by makyen**
This PR combines the commits from #853 and #854.

The intent is to resolve the CI and build issues as a result of the Mimemagic package yanking version 0.3.5. See Issue #849 for more information.

### CODE REVIEW

**Comment by makyen** [comment]
This should not be merged into the master branch until all of the CI tests pass.

**Comment by makyen** [comment]
@user12986714 In case it wasn't clear what happened, I combined your two commits into this single PR in order to be able to see what the overall result is of both commits combined, without having to merge them into the master branch. There are still issues with the rails-tests part of the CI testing. The CircleCI testing gets further than the GitHub Action CI testing, so you'll probably want to look at both.

**Comment by user12986714** [comment]
There appears to be an issue with our github CI config `Can't connect to MySQL server on '127.0.0.1'`

**Comment by user12986714** [comment]
```patch
@@ -29,6 +29,22 @@
     raise ActionController::RoutingError, 'Not Found'
   end

+  def after_sign_in_path_for(resource_or_scope)
+    if current_user.username.nil?
+      users_username_path
+    elsif current_user.stack_exchange_account_id.nil?
+      authentication_status_path
+    else
+      stored_location = nil
+      begin
+        stored_location = stored_location_for(resource_or_scope)
+      rescue # rubocop:disable Lint/HandleExceptions
+      end
+
+      request.env['omniauth.origin'] || stored_location || root_path
+    end
+  end
+
   def redis_log(_msg)
     # redis = redis(logger: true)
     # redis.multi do |m|
@@ -128,8 +144,4 @@
   def location_storable?
     request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
   end
-
-  def after_sign_in_path_for(resource)
-    stored_location_for(resource) || super
-  end
 end
```

Looks like this patch will fix the issues

**Comment by makyen** [comment]
@user12986714 If that will fix the issues, then please submit a PR which does that. You should be able to do so against the branch which is used for this PR. Alternately, you can submit a PR with all three commits and we can discard this one. My intent with creating this PR wasn't to usurp you working on this, but only to put both of your commits in one PR, so we could see if there were still issues which needed to be resolved prior to merging into the master branch.

**Comment by user12986714** [comment]
I am not aware of the ability to open a PR against another PR (hence the
patch, which you can apply using `patch (1)`)... How can I actually do that?

**Comment by makyen** [comment]
@user12986714 You should be able to select the branch into which you desire to merge from among any existing branch within the repository. This PR is based on just another branch, as are all PRs. In this case, the branch is "Mak-combined-fix-for-mimemagic-issue".

**Pull request merged**
