### PR TITLE
Don't double nullify flag logs

### PR DESCRIPTION
**Pull request by user12986714**
`flag_logs` is already associated with
```ruby
has_many :flag_logs, dependent: :nullify
```

### CODE REVIEW

**Comment by user12986714** [comment]
Might be the cause of losing flag logs.

**Comment by user12986714** [comment]
I thought the foreign key constraint is removed on d845bd91 ...

**Comment by user12986714** [comment]
Using `unscoped` on associated model will cause the return of all model **regardless the association**, effectively nuking all flag logs.

**Comment by thesecretmaster** [comment]
I'm not quite sure why we're removing the foreign key, but removing that before_destroy callback looks good to me.

**Comment by user12986714** [comment]
@thesecretmaster Otherwise we can't delete user due to foreign key constraints; see CI log for the first commit.

**Comment by thesecretmaster** [comment]
Yeah, but shouldn't the flag logs user_id field get nullified before the deletion, making it a non-issue?

**Comment by user12986714** [comment]
@thesecretmaster But... CI does not agree with this; looks like it is nullified *after* the deletion of the db row in table Users, which will cause the action of deleting the Users row to fail.

**Comment by thesecretmaster** [comment]
Yeah, but I think the fix should be to troubleshoot the order in which those things happen, not remove the constraint. There's nothing wrong with the constraint as far as I can tell.

**Comment by ArtOfCode-** [comment]
Eh, Rails fudges FK constraints anyway

**Pull request merged**
