### PR TITLE
Developer tools

### PR DESCRIPTION
**Pull request by ArtOfCode-**
- New `:developer` role
- Some tools for devs:
  - Site cache manual updates (not sure how useful this is going to be, but hey)
  - Production log viewer
- Also updated the mailer so that it copies me when Smokey breaks

PR'd so it can get some feedback first - are we happy with the prod log being available to devs, in particular?

### CODE REVIEW

**Comment by Undo1** [comment]
I'm still not completely comfortable with it, but I can't articulate *why* so maybe it's unfounded. 

The only PII in there should be emails and IPs... it might be fairly easy to regex those out, if we wanted to. Neither are terribly high priority, but I do believe we should protect them where we can.

**Comment by ArtOfCode-** [comment]
@Undo1 Emails shouldn't be too hard to regex out. IPs... do we need to protect IPs? They're not PII.

**Comment by AWegnerGitHub** [comment]
SE protects them as PII

**Comment by ArtOfCode-** [comment]
True. That said, do we need to follow SE's standards?

**Comment by Undo1** [comment]
Andy beat me to it. Are they really PII? Ehh, not sure... but they're a darn simple regex to filter for. Do we have a reason to see them?

**Comment by ArtOfCode-** [comment]
I can filter out IPs easy enough. @Undo1, can you come up with a regex for emails that (a) isn't RFC 2822-compliant (i.e. not ten miles long) and (b) works for all the emails currently in the metasmoke DB?

**Comment by Undo1** [comment]
@ArtOfCode- `/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i`, from http://stackoverflow.com/a/8219213/1849664

**Comment by ArtOfCode-** [comment]
@Undo1 cheers, filtered

**Comment by Undo1** [comment]
Planning to merge tomorrow.

**Comment by ArtOfCode-** [comment]
@Undo1 24681f8 Ah. Can you tell I've never used rolify before? :)

**Pull request merged**
