### PR TITLE
Actually display 50+

### PR DESCRIPTION
**Pull request by user12986714**
image
Related: 88b6421

### CODE REVIEW

**Comment by makyen** [comment]
While I believe this is as ArtOfCode- intended, I'd appreciate it if we still display the actual number to admins.

**Comment by ArtOfCode-** [comment]
Looks good other than the failing tests - those'll need fixing.

**Comment by user12986714** [comment]
No idea why the circleci test failed, as [this test](https://github.com/Charcoal-SE/metasmoke/pull/754/checks?check_run_id=865903701) succeeded.

**Comment by ArtOfCode-** [comment]
Nor me, but it looks like a credible failure, so it needs fixing

**Pull request merged**
