### PR TITLE
Actually restrict db dumps to core users

### PR DESCRIPTION
**Pull request by user12986714**
Currently it appears that anyone with the correct url can obtain the db and redis dump.

### CODE REVIEW

**Comment by thesecretmaster** [comment]
Pretty sure this is status-bydesign, although feel free to correct me if someone knows better.

**Comment by user12986714** [comment]
@thesecretmaster https://charcoal-se.org/smokey/Privileges#core-ms
```
Ability to download database dumps*
```

**Comment by thesecretmaster** [comment]
Ah right, IIRC this had something to do with S3 usage/costs (cc @Undo1?) If that's still true than we should make it visible to Core users in the navbar (see `app/views/layouts/application.html.erb`), if that's not true post-server-migration then I think we should leave it open to everyone and correct the wiki.

**Comment by teward** [comment]
We currently disabled backup dumps for DB and such so having the URL won't do anything for now.  Redis dumps aren't regularly available as far as I can tell, even when we were running daily DB backups.

Further, the DB dumps are uploaded to S3 and only in sanitized form (no PII is leaked in them) which is good for statistical analysis and other analysis people want to do on the data.  And because PII is stripped from the SQL dumps it's a non-issue if non-core people have access since they can just ask for the distribution anyways:

> * Although downloading database dumps is restricted to core users, you’re welcome to distribute them onwards to other people who ask for them too.

Certain ones of us with God Access to the machine have full access to the database though, including the un-sanitized dumps - this is for backup purposes and for recovery purposes, or for certain levels of testing such as trying to debug DB level problems or DB index issues or such.

This is by-design and overall not really a 'concern' since the sanitized dumps can be distributed freely if someone asks someone with Core access to pull a dump.  It's the private DB dumps we have to worry about sharing, and those only reside in heavily-secured backups I maintain currently in the infrastructure.

**Comment by thesecretmaster** [comment]
I think the reason for the core + distribution thing is that the dumps were rather large and we didn't want to rack up Undo's S3 bill. So I think we'd stick with core only + distributing if they'll still be hosted on S3.

**Comment by teward** [comment]
> Also cc @teward about where DB dumps will be hosted once they're back up? Will they still be S3 or will they be hosted off the same box as MS?

Currently, there are no DB dumps available because of me still building out the replacement to Metasmoke and Ruby trying to DB dump and breaking things.  If we want we can host the single files off of the Metasmoke instance itself, or we can spin S3 style hosting dumps in my own environment with S3 compatible storage infrastructure.  The only place we'd keep multiple backups is for the unsanitized DB storage in my own highly-secure backup systems for recovery purposes - I keep at least weekly backups in storage right now in the prototype system for DB backups)

Given that I have zero actual data bandwidth caps we should be able to host the backups right from MS and serve direct (or run it via S3 compatible storage locally).

However, in either of the last two statements, we don't *need* to enforce the Core requirement because there's no cost for storage in my infrastructure other than my power bill.

**Comment by user12986714** [comment]
SD privileges wiki has been changed to reflect this.

**Comment by teward** [comment]
> I think the reason for the core + distribution thing is that the dumps were rather large and we didn't want to rack up Undo's S3 bill. So I think we'd stick with core only + distributing if they'll still be hosted on S3.

Yep, you're right, this was because of S3 costs, per Undo:

> The reason before was to keep someone we've irritated from downloading it nine million times and ballooning the S3 bandwidth out cost.

With us moving to on-server copies of the DB and sharing them directly from the Metasmoke server, plus a few dozen security controls on the network border, we no longer need to enforce Core restrictions for DB access.

**Pull request closed without merging**
