### PR TITLE
Clean up after the token migration beta

### PR DESCRIPTION
**Pull request by thesecretmaster**
I think I did most of this, but do we want to do more, like renaming the `token_migrated` column?

### CODE REVIEW

**Comment by ArtOfCode-** [comment]
LGTM, assuming those test failures are unrelated/inconsequential

**Comment by thesecretmaster** [comment]
Those tests definitely need fixing, thanks for pointing it out.

**Comment by ArtOfCode-** [comment]
Poke?

**Comment by thesecretmaster** [comment]
Still haven't had time, feel free to pick it up if you want to.

**Pull request closed without merging**
